"""initial research persistence

Revision ID: 03a8779c3f27
Revises:
Create Date: 2026-08-14 17:34:06.500799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03a8779c3f27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('collector_version', sa.String(length=128), nullable=False),
    sa.Column('configuration_sha256', sa.String(length=64), nullable=False),
    sa.Column('configuration_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failure_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('persisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed', 'cancelled')", name='ck_collector_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collector_runs_started_at', 'collector_runs', ['started_at'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('first_discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('persisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain', 'address', name='uq_tokens_chain_address')
    )
    op.create_table('api_request_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collector_run_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=256), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload_sha256', sa.String(length=64), nullable=True),
    sa.Column('failure_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('persisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('succeeded', 'empty', 'partial', 'failed', 'throttled', 'malformed')", name='ck_api_request_log_outcome'),
    sa.ForeignKeyConstraint(['collector_run_id'], ['collector_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_api_request_log_idempotency_key')
    )
    op.create_index('ix_api_request_log_collector_run_id', 'api_request_log', ['collector_run_id'], unique=False)
    op.create_index('ix_api_request_log_provider_requested_at', 'api_request_log', ['provider', 'requested_at'], unique=False)
    op.create_table('discovery_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_event_id', sa.String(length=256), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('persisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_discovery_events_idempotency_key')
    )
    op.create_index('ix_discovery_events_provider_source_event_at', 'discovery_events', ['provider', 'source_event_at'], unique=False)
    op.create_index('ix_discovery_events_token_received_at', 'discovery_events', ['token_id', 'received_at'], unique=False)
    op.create_table('lifecycle_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('previous_state', sa.String(length=64), nullable=True),
    sa.Column('new_state', sa.String(length=64), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_watermark', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason_code', sa.String(length=128), nullable=False),
    sa.Column('reason_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('configuration_sha256', sa.String(length=64), nullable=False),
    sa.Column('configuration_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('persisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_lifecycle_events_idempotency_key')
    )
    op.create_index('ix_lifecycle_events_token_decided_at', 'lifecycle_events', ['token_id', 'decided_at'], unique=False)
    op.create_table('pairs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_id', sa.Uuid(), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('dex_identifier', sa.String(length=128), nullable=True),
    sa.Column('first_discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('persisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain', 'address', name='uq_pairs_chain_address')
    )
    op.create_index('ix_pairs_token_id', 'pairs', ['token_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pair_id', sa.Uuid(), nullable=False),
    sa.Column('api_request_log_id', sa.Uuid(), nullable=False),
    sa.Column('source_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_record_locator', sa.String(length=256), nullable=True),
    sa.Column('source_record_sha256', sa.String(length=64), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('price_native', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('liquidity_usd', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('market_cap_usd', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('fully_diluted_valuation_usd', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('volume_m5_usd', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('volume_h1_usd', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('volume_h6_usd', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('volume_h24_usd', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('price_change_m5_pct', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('price_change_h1_pct', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('price_change_h6_pct', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('price_change_h24_pct', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('buys_m5', sa.BigInteger(), nullable=True),
    sa.Column('sells_m5', sa.BigInteger(), nullable=True),
    sa.Column('buys_h1', sa.BigInteger(), nullable=True),
    sa.Column('sells_h1', sa.BigInteger(), nullable=True),
    sa.Column('persisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_request_log_id'], ['api_request_log.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pair_id'], ['pairs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('received_at', 'id', name='pk_observations'),
    sa.UniqueConstraint('received_at', 'api_request_log_id', 'pair_id', name='uq_observations_request_pair'),
    postgresql_partition_by='RANGE (received_at)'
    )
    op.create_index('ix_observations_pair_received_at', 'observations', ['pair_id', 'received_at'], unique=False)
    op.execute(
        """
        DO $$
        DECLARE
            partition_start date;
        BEGIN
            FOR partition_start IN
                SELECT generate_series(DATE '2026-01-01', DATE '2027-12-01', INTERVAL '1 month')::date
            LOOP
                EXECUTE format(
                    'CREATE TABLE observations_%s PARTITION OF observations FOR VALUES FROM (%L) TO (%L)',
                    to_char(partition_start, 'YYYY_MM'),
                    partition_start,
                    (partition_start + INTERVAL '1 month')::date
                );
            END LOOP;
        END $$;
        """
    )
    op.execute(
        """
        CREATE FUNCTION prevent_immutable_table_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% rows are immutable', TG_TABLE_NAME USING ERRCODE = '55000';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table_name in (
        "api_request_log",
        "discovery_events",
        "lifecycle_events",
        "observations",
    ):
        op.execute(
            f"CREATE TRIGGER {table_name}_immutable "
            f"BEFORE UPDATE OR DELETE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION prevent_immutable_table_mutation()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in (
        "observations",
        "lifecycle_events",
        "discovery_events",
        "api_request_log",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS {table_name}_immutable ON {table_name}")
    op.execute("DROP FUNCTION IF EXISTS prevent_immutable_table_mutation()")
    op.drop_index('ix_observations_pair_received_at', table_name='observations')
    op.drop_table('observations')
    op.drop_index('ix_pairs_token_id', table_name='pairs')
    op.drop_table('pairs')
    op.drop_index('ix_lifecycle_events_token_decided_at', table_name='lifecycle_events')
    op.drop_table('lifecycle_events')
    op.drop_index('ix_discovery_events_token_received_at', table_name='discovery_events')
    op.drop_index('ix_discovery_events_provider_source_event_at', table_name='discovery_events')
    op.drop_table('discovery_events')
    op.drop_index('ix_api_request_log_provider_requested_at', table_name='api_request_log')
    op.drop_index('ix_api_request_log_collector_run_id', table_name='api_request_log')
    op.drop_table('api_request_log')
    op.drop_table('tokens')
    op.drop_index('ix_collector_runs_started_at', table_name='collector_runs')
    op.drop_table('collector_runs')
    # ### end Alembic commands ###
