"""add selective security enrichment

Revision ID: f63b7d9a20ce
Revises: e52a1c9d704f
Create Date: 2026-08-22 07:44:09.999248

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f63b7d9a20ce"
down_revision: Union[str, Sequence[str], None] = "e52a1c9d704f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "security_enrichment_policies",
        sa.Column("policy_sha256", sa.String(length=64), nullable=False),
        sa.Column("policy_name", sa.String(length=128), nullable=False),
        sa.Column("policy_version", sa.String(length=32), nullable=False),
        sa.Column("policy_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "persisted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("policy_sha256"),
    )
    op.create_table(
        "security_feature_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("semantic_key", sa.String(length=64), nullable=False),
        sa.Column("token_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("collection_epoch_id", sa.Uuid(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acquisition_mode", sa.String(length=40), nullable=False),
        sa.Column("feature_set_name", sa.String(length=64), nullable=False),
        sa.Column("feature_set_version", sa.String(length=32), nullable=False),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_fact_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column("schema_sha256", sa.String(length=64), nullable=False),
        sa.Column("policy_sha256", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "persisted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "acquisition_mode IN ('historically_available', 'retrospectively_reconstructed')",
            name="ck_security_features_acquisition",
        ),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate_events.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["collection_epoch_id"], ["collection_epochs.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["policy_sha256"], ["security_enrichment_policies.policy_sha256"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("semantic_key", name="uq_security_features_semantic"),
    )
    op.create_index(
        "ix_security_features_token_received",
        "security_feature_snapshots",
        ["token_id", "received_at"],
        unique=False,
    )
    op.create_table(
        "wallet_cluster_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("semantic_key", sa.String(length=64), nullable=False),
        sa.Column("cluster_id", sa.String(length=64), nullable=False),
        sa.Column("token_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acquisition_mode", sa.String(length=40), nullable=False),
        sa.Column("algorithm_version", sa.String(length=64), nullable=False),
        sa.Column("input_edge_sha256", sa.String(length=64), nullable=False),
        sa.Column("members", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "persisted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "acquisition_mode IN ('historically_available', 'retrospectively_reconstructed')",
            name="ck_wallet_clusters_acquisition",
        ),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate_events.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("semantic_key", name="uq_wallet_clusters_semantic"),
    )
    op.create_index(
        "ix_wallet_clusters_token_generated",
        "wallet_cluster_snapshots",
        ["token_id", "generated_at"],
        unique=False,
    )
    op.create_table(
        "security_provider_budget_reservations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("semantic_key", sa.String(length=64), nullable=False),
        sa.Column("candidate_task_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("budget_class", sa.String(length=64), nullable=False),
        sa.Column("reserved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "persisted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_task_id"], ["candidate_enrichment_tasks.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("semantic_key", name="uq_security_provider_budget_semantic"),
    )
    op.create_index(
        "ix_security_provider_budget_provider_reserved",
        "security_provider_budget_reservations",
        ["provider", "reserved_at"],
        unique=False,
    )
    op.create_table(
        "security_provider_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("semantic_key", sa.String(length=64), nullable=False),
        sa.Column("candidate_task_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("token_id", sa.Uuid(), nullable=False),
        sa.Column("collection_epoch_id", sa.Uuid(), nullable=False),
        sa.Column("collector_run_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("provider_schema_version", sa.String(length=32), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("completeness", sa.String(length=32), nullable=False),
        sa.Column("acquisition_mode", sa.String(length=40), nullable=False),
        sa.Column("source_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_slot", sa.BigInteger(), nullable=True),
        sa.Column("page_cursor", sa.String(length=256), nullable=True),
        sa.Column("next_cursor", sa.String(length=256), nullable=True),
        sa.Column("http_status_code", sa.Integer(), nullable=True),
        sa.Column("request_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("response_payload_sha256", sa.String(length=64), nullable=True),
        sa.Column("failure_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "persisted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "acquisition_mode IN ('historically_available', 'retrospectively_reconstructed')",
            name="ck_security_provider_requests_acquisition",
        ),
        sa.CheckConstraint(
            "completeness IN ('full_distribution', 'top_20_token_accounts', 'closed_time_range', 'partial_pagination', 'bounded_graph', 'unknown')",
            name="ck_security_provider_requests_completeness",
        ),
        sa.CheckConstraint(
            "outcome IN ('available', 'partial', 'unavailable', 'failed')",
            name="ck_security_provider_requests_outcome",
        ),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate_events.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["candidate_task_id"], ["candidate_enrichment_tasks.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["collection_epoch_id"], ["collection_epochs.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["collector_run_id"], ["collector_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("semantic_key", name="uq_security_provider_requests_semantic"),
    )
    op.create_index(
        "ix_security_provider_requests_provider_at",
        "security_provider_requests",
        ["provider", "requested_at"],
        unique=False,
    )
    op.create_index(
        "ix_security_provider_requests_task",
        "security_provider_requests",
        ["candidate_task_id"],
        unique=False,
    )
    op.create_table(
        "creator_history_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("semantic_key", sa.String(length=64), nullable=False),
        sa.Column("token_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_task_id", sa.Uuid(), nullable=False),
        sa.Column("provider_request_id", sa.Uuid(), nullable=False),
        sa.Column("collection_epoch_id", sa.Uuid(), nullable=False),
        sa.Column("creator_wallet", sa.String(length=128), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("availability", sa.String(length=16), nullable=False),
        sa.Column("acquisition_mode", sa.String(length=40), nullable=False),
        sa.Column("prior_token_count", sa.Integer(), nullable=True),
        sa.Column("prior_tracked_launches", sa.Integer(), nullable=True),
        sa.Column("prior_collapse_count", sa.Integer(), nullable=True),
        sa.Column("prior_large_winner_count", sa.Integer(), nullable=True),
        sa.Column("median_survival_seconds", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("mean_survival_seconds", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("launches_last_30d", sa.Integer(), nullable=True),
        sa.Column("creator_hold_pct", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("source_token_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column("policy_sha256", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "persisted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "acquisition_mode IN ('historically_available', 'retrospectively_reconstructed')",
            name="ck_creator_history_acquisition",
        ),
        sa.CheckConstraint(
            "availability IN ('available', 'partial', 'unavailable', 'failed')",
            name="ck_creator_history_availability",
        ),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate_events.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["candidate_task_id"], ["candidate_enrichment_tasks.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["collection_epoch_id"], ["collection_epochs.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["policy_sha256"], ["security_enrichment_policies.policy_sha256"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["provider_request_id"], ["security_provider_requests.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("semantic_key", name="uq_creator_history_semantic"),
    )
    op.create_index(
        "ix_creator_history_wallet_received",
        "creator_history_snapshots",
        ["creator_wallet", "received_at"],
        unique=False,
    )
    op.create_table(
        "creator_relationship_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("semantic_key", sa.String(length=64), nullable=False),
        sa.Column("token_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("provider_request_id", sa.Uuid(), nullable=False),
        sa.Column("creator_wallet", sa.String(length=128), nullable=False),
        sa.Column("relationship_type", sa.String(length=64), nullable=False),
        sa.Column("source_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acquisition_mode", sa.String(length=40), nullable=False),
        sa.Column("source_fact_identity", sa.String(length=256), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "persisted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "acquisition_mode IN ('historically_available', 'retrospectively_reconstructed')",
            name="ck_creator_relationship_acquisition",
        ),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate_events.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["provider_request_id"], ["security_provider_requests.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("semantic_key", name="uq_creator_relationship_semantic"),
    )
    op.create_index(
        "ix_creator_relationship_token_received",
        "creator_relationship_events",
        ["token_id", "received_at"],
        unique=False,
    )
    op.create_index(
        "ix_creator_relationship_wallet_received",
        "creator_relationship_events",
        ["creator_wallet", "received_at"],
        unique=False,
    )
    op.create_table(
        "funding_relationship_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("semantic_key", sa.String(length=64), nullable=False),
        sa.Column("token_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("provider_request_id", sa.Uuid(), nullable=False),
        sa.Column("wallet", sa.String(length=128), nullable=False),
        sa.Column("funding_source", sa.String(length=128), nullable=False),
        sa.Column("funding_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("amount_lamports", sa.BigInteger(), nullable=True),
        sa.Column("hop_depth", sa.Integer(), nullable=False),
        sa.Column("source_signature", sa.String(length=128), nullable=False),
        sa.Column("completeness", sa.String(length=32), nullable=False),
        sa.Column("acquisition_mode", sa.String(length=40), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "persisted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "acquisition_mode IN ('historically_available', 'retrospectively_reconstructed')",
            name="ck_funding_relationship_acquisition",
        ),
        sa.CheckConstraint(
            "completeness IN ('full_distribution', 'top_20_token_accounts', 'closed_time_range', 'partial_pagination', 'bounded_graph', 'unknown')",
            name="ck_funding_relationship_completeness",
        ),
        sa.CheckConstraint("hop_depth BETWEEN 1 AND 2", name="ck_funding_relationship_depth"),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate_events.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["provider_request_id"], ["security_provider_requests.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("semantic_key", name="uq_funding_relationship_semantic"),
    )
    op.create_index(
        "ix_funding_relationship_token_received",
        "funding_relationship_evidence",
        ["token_id", "received_at"],
        unique=False,
    )
    op.create_table(
        "holder_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("semantic_key", sa.String(length=64), nullable=False),
        sa.Column("token_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_task_id", sa.Uuid(), nullable=False),
        sa.Column("provider_request_id", sa.Uuid(), nullable=False),
        sa.Column("collection_epoch_id", sa.Uuid(), nullable=False),
        sa.Column("source_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("availability", sa.String(length=16), nullable=False),
        sa.Column("completeness", sa.String(length=32), nullable=False),
        sa.Column("acquisition_mode", sa.String(length=40), nullable=False),
        sa.Column("source_slot", sa.BigInteger(), nullable=True),
        sa.Column("mint_supply_raw", sa.Numeric(precision=78, scale=0), nullable=True),
        sa.Column("holder_count", sa.BigInteger(), nullable=True),
        sa.Column("top_1_pct", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("top_5_pct", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("top_10_pct", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("top_20_pct", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("largest_holder_pct", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("largest_non_pool_holder_pct", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("creator_holder_pct", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("hhi", sa.Numeric(precision=24, scale=18), nullable=True),
        sa.Column("covered_supply_pct", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("holder_growth", sa.BigInteger(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column("policy_sha256", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "persisted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "acquisition_mode IN ('historically_available', 'retrospectively_reconstructed')",
            name="ck_holder_snapshots_acquisition",
        ),
        sa.CheckConstraint(
            "availability IN ('available', 'partial', 'unavailable', 'failed')",
            name="ck_holder_snapshots_availability",
        ),
        sa.CheckConstraint(
            "completeness IN ('full_distribution', 'top_20_token_accounts', 'closed_time_range', 'partial_pagination', 'bounded_graph', 'unknown')",
            name="ck_holder_snapshots_completeness",
        ),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate_events.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["candidate_task_id"], ["candidate_enrichment_tasks.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["collection_epoch_id"], ["collection_epochs.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["policy_sha256"], ["security_enrichment_policies.policy_sha256"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["provider_request_id"], ["security_provider_requests.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("semantic_key", name="uq_holder_snapshots_semantic"),
    )
    op.create_index(
        "ix_holder_snapshots_token_received",
        "holder_snapshots",
        ["token_id", "received_at"],
        unique=False,
    )
    op.create_table(
        "liquidity_event_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("semantic_key", sa.String(length=64), nullable=False),
        sa.Column("token_id", sa.Uuid(), nullable=False),
        sa.Column("pair_id", sa.Uuid(), nullable=True),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("provider_request_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("source_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("availability", sa.String(length=16), nullable=False),
        sa.Column("acquisition_mode", sa.String(length=40), nullable=False),
        sa.Column("source_slot", sa.BigInteger(), nullable=True),
        sa.Column("signature", sa.String(length=128), nullable=True),
        sa.Column("base_delta", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("quote_delta", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("liquidity_usd_before", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("liquidity_usd_after", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("removal_pct", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("lp_wallet", sa.String(length=128), nullable=True),
        sa.Column("source_fact_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decoder_version", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "persisted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "acquisition_mode IN ('historically_available', 'retrospectively_reconstructed')",
            name="ck_liquidity_event_acquisition",
        ),
        sa.CheckConstraint(
            "availability IN ('available', 'partial', 'unavailable', 'failed')",
            name="ck_liquidity_event_availability",
        ),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate_events.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["pair_id"], ["pairs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["provider_request_id"], ["security_provider_requests.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("semantic_key", name="uq_liquidity_event_semantic"),
    )
    op.create_index(
        "ix_liquidity_event_pair_source",
        "liquidity_event_evidence",
        ["pair_id", "source_event_at"],
        unique=False,
    )
    op.create_index(
        "ix_liquidity_event_token_received",
        "liquidity_event_evidence",
        ["token_id", "received_at"],
        unique=False,
    )
    op.create_table(
        "trader_distribution_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("semantic_key", sa.String(length=64), nullable=False),
        sa.Column("token_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_task_id", sa.Uuid(), nullable=False),
        sa.Column("provider_request_id", sa.Uuid(), nullable=False),
        sa.Column("collection_epoch_id", sa.Uuid(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("availability", sa.String(length=16), nullable=False),
        sa.Column("completeness", sa.String(length=32), nullable=False),
        sa.Column("acquisition_mode", sa.String(length=40), nullable=False),
        sa.Column("unique_buyers", sa.BigInteger(), nullable=True),
        sa.Column("unique_sellers", sa.BigInteger(), nullable=True),
        sa.Column("unique_traders", sa.BigInteger(), nullable=True),
        sa.Column("total_trades", sa.BigInteger(), nullable=False),
        sa.Column("buy_trades", sa.BigInteger(), nullable=False),
        sa.Column("sell_trades", sa.BigInteger(), nullable=False),
        sa.Column("volume_usd", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("median_trade_usd", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("p90_trade_usd", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("p95_trade_usd", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("largest_trade_usd", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("top_1_trader_volume_share", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("top_5_trader_volume_share", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("top_10_trader_volume_share", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("repeat_trader_ratio", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("new_wallet_ratio", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("buy_sell_wallet_overlap", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("source_fact_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column("policy_sha256", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "persisted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "acquisition_mode IN ('historically_available', 'retrospectively_reconstructed')",
            name="ck_trader_distribution_acquisition",
        ),
        sa.CheckConstraint(
            "availability IN ('available', 'partial', 'unavailable', 'failed')",
            name="ck_trader_distribution_availability",
        ),
        sa.CheckConstraint(
            "completeness IN ('full_distribution', 'top_20_token_accounts', 'closed_time_range', 'partial_pagination', 'bounded_graph', 'unknown')",
            name="ck_trader_distribution_completeness",
        ),
        sa.CheckConstraint("window_end > window_start", name="ck_trader_distribution_window"),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate_events.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["candidate_task_id"], ["candidate_enrichment_tasks.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["collection_epoch_id"], ["collection_epochs.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["policy_sha256"], ["security_enrichment_policies.policy_sha256"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["provider_request_id"], ["security_provider_requests.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("semantic_key", name="uq_trader_distribution_semantic"),
    )
    op.create_index(
        "ix_trader_distribution_token_received",
        "trader_distribution_snapshots",
        ["token_id", "received_at"],
        unique=False,
    )
    op.create_table(
        "wallet_relationship_edges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("semantic_key", sa.String(length=64), nullable=False),
        sa.Column("token_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("provider_request_id", sa.Uuid(), nullable=False),
        sa.Column("wallet_a", sa.String(length=128), nullable=False),
        sa.Column("wallet_b", sa.String(length=128), nullable=False),
        sa.Column("relationship_type", sa.String(length=64), nullable=False),
        sa.Column("first_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("strength_count", sa.Integer(), nullable=False),
        sa.Column("acquisition_mode", sa.String(length=40), nullable=False),
        sa.Column("source_fact_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("method_version", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "persisted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "acquisition_mode IN ('historically_available', 'retrospectively_reconstructed')",
            name="ck_wallet_edges_acquisition",
        ),
        sa.CheckConstraint("wallet_a <> wallet_b", name="ck_wallet_edges_distinct"),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate_events.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["provider_request_id"], ["security_provider_requests.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("semantic_key", name="uq_wallet_edges_semantic"),
    )
    op.create_index(
        "ix_wallet_edges_token_received",
        "wallet_relationship_edges",
        ["token_id", "evidence_received_at"],
        unique=False,
    )
    op.create_table(
        "holder_balance_facts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("holder_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("token_account", sa.String(length=128), nullable=False),
        sa.Column("owner_wallet", sa.String(length=128), nullable=True),
        sa.Column("raw_balance", sa.Numeric(precision=78, scale=0), nullable=False),
        sa.Column("balance_pct", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("is_known_pool", sa.Boolean(), nullable=False),
        sa.Column("is_creator", sa.Boolean(), nullable=False),
        sa.Column("exclusion_reason", sa.String(length=256), nullable=True),
        sa.Column("source_fact_identity", sa.String(length=256), nullable=False),
        sa.Column(
            "persisted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["holder_snapshot_id"], ["holder_snapshots.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "holder_snapshot_id", "token_account", name="uq_holder_balance_account"
        ),
    )
    op.create_index(
        "ix_holder_balance_wallet", "holder_balance_facts", ["owner_wallet"], unique=False
    )
    for table in (
        "security_enrichment_policies",
        "security_feature_snapshots",
        "wallet_cluster_snapshots",
        "security_provider_budget_reservations",
        "security_provider_requests",
        "creator_history_snapshots",
        "creator_relationship_events",
        "funding_relationship_evidence",
        "holder_snapshots",
        "liquidity_event_evidence",
        "trader_distribution_snapshots",
        "wallet_relationship_edges",
        "holder_balance_facts",
    ):
        op.execute(
            f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION prevent_immutable_table_mutation()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_holder_balance_wallet", table_name="holder_balance_facts")
    op.drop_table("holder_balance_facts")
    op.drop_index("ix_wallet_edges_token_received", table_name="wallet_relationship_edges")
    op.drop_table("wallet_relationship_edges")
    op.drop_index(
        "ix_trader_distribution_token_received", table_name="trader_distribution_snapshots"
    )
    op.drop_table("trader_distribution_snapshots")
    op.drop_index("ix_liquidity_event_token_received", table_name="liquidity_event_evidence")
    op.drop_index("ix_liquidity_event_pair_source", table_name="liquidity_event_evidence")
    op.drop_table("liquidity_event_evidence")
    op.drop_index("ix_holder_snapshots_token_received", table_name="holder_snapshots")
    op.drop_table("holder_snapshots")
    op.drop_index(
        "ix_funding_relationship_token_received", table_name="funding_relationship_evidence"
    )
    op.drop_table("funding_relationship_evidence")
    op.drop_index(
        "ix_creator_relationship_wallet_received", table_name="creator_relationship_events"
    )
    op.drop_index(
        "ix_creator_relationship_token_received", table_name="creator_relationship_events"
    )
    op.drop_table("creator_relationship_events")
    op.drop_index("ix_creator_history_wallet_received", table_name="creator_history_snapshots")
    op.drop_table("creator_history_snapshots")
    op.drop_index("ix_security_provider_requests_task", table_name="security_provider_requests")
    op.drop_index(
        "ix_security_provider_requests_provider_at", table_name="security_provider_requests"
    )
    op.drop_table("security_provider_requests")
    op.drop_index(
        "ix_security_provider_budget_provider_reserved",
        table_name="security_provider_budget_reservations",
    )
    op.drop_table("security_provider_budget_reservations")
    op.drop_index("ix_wallet_clusters_token_generated", table_name="wallet_cluster_snapshots")
    op.drop_table("wallet_cluster_snapshots")
    op.drop_index("ix_security_features_token_received", table_name="security_feature_snapshots")
    op.drop_table("security_feature_snapshots")
    op.drop_table("security_enrichment_policies")
    # ### end Alembic commands ###
